### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by ouranos6** [KONNEKTING/KonnektingSuite#12]
Hi,

I'm sorry but how can I run the program?
I didn't see any java binaries...

Best regards,

Ivan

**Comment by tuxedo0801** [comment]
Check out the releases:

https://github.com/KONNEKTING/KonnektingSuite/releases

Download the ZIP for your system/platform, extract it locally and run the included .BAT file.

**Comment by ouranos6** [comment]
Thanks, I didn't see it before you mention!
How can I start the suite in english because my german is quite limited... AND i saw in the i18n folder the language.properties file in english.

**Comment by tuxedo0801** [comment]
beta3 is using german as default and switches to english, if an english system is detected. 

That might run into problem on your system, espscially if it does not (correctly) identify itself with english locale. 

beta4 will fix this. Default is then english, and if german is detected, it will switch to german.

To overcome this issue for now, modify the .BAT files (watch out for "-Duser.language=en"):

KONNEKTING-Suite_DEBUG.bat

```
@echo off
start /B .\jre1.8.0_74\bin\java -Duser.language=en -Dde.root1.slicknx.konnekting.debug=true -Ddebuglevel=ALL -cp .\bin\* de.konnekting.suite.Main
```

KONNEKTING-Suite.bat

```
@echo off
start /B .\jre1.8.0_74\bin\javaw -Duser.language=en -cp .\bin\* de.konnekting.suite.Main

```

The KONNEKTING Device Library is by default set with DEBUG. So to be able to use the suite with your arduino without communication issues, you have to run the debug-enabled Suite. Otherwise programming the arduino will fail.

**Comment by tuxedo0801** [comment]
Closed for now. Beta4 will finally solve it.
