### ISSUE TITLE
Request for new datatype String 

### ISSUE THREAD

**Issue by Adminius** [KONNEKTING/KonnektingSuite#16]
for hardware with display it is necessary to send text-params from suite to KNX-hardware.
e.g.: "East: %d lux"

**Comment by tuxedo0801** [comment]
A kind of limitation:

https://github.com/KONNEKTING/KonnektingDocumentation/blob/master/protocol_general.md

We only have 12 bytes available in a single telegram. So either we limit the String type to 12 bytes, or we have to create a more complex type, which can split larger strings into many telegrams. That would introduce additionaly complexity to arduino code ...

any comment on this?

**Comment by Adminius** [comment]
we can spilt it: 
prefix "East", suffix "lux". 
In this case we have up to 2x 14bytes

**Comment by tuxedo0801** [comment]
not 14, but 12 bytes. Each telegram can have 14 bytes, and we already use 2 bytes for protocol-version and telegram-msg-id.

If you split it up, the required code for this type would be easier/smaller. But it's more complex for the user:

* splittet string with prefix, value and suffix
* it's getting more complex if more than one value needs to be part of the string...

I would rather suggest to concatenate two 12 byte strings to have a "long string", including placeholder for the values. So you would have also two parameters, but instead of (I extended the text to require more than 12 bytes to make make this a better example for string split)

```
parameter prefix string "Light East:" (11 bytes)
(auto added value)
parameter suffix string "lux" (3 bytes)
```

you would have

```
parameterstring 1: "East Light: " (12 bytes)
parameterstring 2: "%d lux" (6 bytes)
```

**Comment by tuxedo0801** [comment]
Implementation is done. Need to test ...

**Comment by tuxedo0801** [comment]
@Adminius 
Any progress on testing this?

**Comment by tuxedo0801** [comment]
String usage on arduini side is still not functional. hex-values seem to be correct (same as in xml), but representation is broken.

**Comment by tuxedo0801** [comment]
String works now as well.

API:

`String myString = getSTRING11Param(myIndex);`

If string has to be printen with our debughelper, use s.c_str() to get sting as characters.
