### ISSUE TITLE
Add posibility to handle "Configuration Templates" in the "not so near" future

### ISSUE THREAD

**Issue by hasselk** [KONNEKTING/KonnektingSuite#6]
i mean the ability to export and reimport just the Config(GA, Parameters) of the Device, maybe even a subset ;)

**Comment by tuxedo0801** [comment]
Please explain more in detail. No idea what this is about...

You can just place a .kconfig.xml file in your project folder and the Suite will read it (kind of "import"). You can also backup your Files from project-folder somewhere (kind of "export").

**Comment by tuxedo0801** [comment]
Waiting for feedback ...

**Comment by hasselk** [comment]
when you develop and change your device, it would be nice to be able to load GA or parameters from a xml file to an existing device without manualy editing the xml file of your device. Maybe making it possible to export your ets project and import those changes(GA) to the Device in the Konnecting suite.
without the need to manualy change the devices xml in konnecting project and then restarting the suite.

i hope this is clearer now?!, and im not the only one who likes that

**Comment by tuxedo0801** [comment]
No, it's not that clear, sorry :-(
Maybe we should first make clear what we mean... I'll try:

"Developing a device" would mean:

Create the XML "by hand", espcially the "<device>" element an it's childs (specification of params and com-objects), according to https://github.com/KONNEKTING/KonnektingDocumentation/blob/master/konnekting_xml_device_description.md

"Changing a device" would mean:

Use the suite to create the configuration-part of the XML via Suite's user-interface.

----

> it would be nice to be able to load GA or parameters from a xml file to an existing device without manualy editing the xml file of your device. 

I'm not quite sure what this is about. 
Is this a import-functionality to import com-object's GA and device's params to a device in the suite?
Where does this data come from? And how is the imported data (especially the GAs) mapped to the device's ComObjects?

> Maybe making it possible to export your ets project and import those changes(GA) to the Device in the Konnecting suite.

I already have a library that allows reading/parsing an exported ETS4 (only 4 at the moment...) project. With that, it would be possible to have the GAs in the suite. 
I can think of a feature that would work as follows:

* double-click in GA field in Suite's device->com-obj tab. A dialog opens and presents all GAs from imported ETS4 project, so that the user can choose from this GA list. The user can then apply one of those adresses or simply cancel the dialog and enter the value himself. 

But you where also talking about params... An exported ETS4 projects also contains the params. But:

* they are not yet readable/parseable by my ETS4 project parser AND 
* it would not make sense to have them in the suite, 'cause those are different devices.

So is it about a kind of pick-list so that use end-user of the suite does not need to enter the GAs all by hand but pick them from a existing (imported ETS4 project) list?

**Comment by tuxedo0801** [comment]
Still waiting for feedback ...

**Comment by tuxedo0801** [comment]
Closed, as no feedback received within last 2 months.
