### ISSUE TITLE
KONNEKTING Suite fails when VirtualBox Host-Only Network ist active

### ISSUE THREAD

**Issue by junibart** [KONNEKTING/KonnektingSuite#7]
Hi,

KONNEKTING Suite start failed since I installed Virtual Box on my PC (Window 10, 64bit). 

A Suite start is possible by either

- attach a LAN-cable instead of WLan or
- disable VirtualBox Host-Only Network in control panel. 

An error log is attached. It would be nice if KONNKTING could start without problems with vbox network adapters. Alternatively, check and give information in the release notes. 

best regards,
junibart

[KonnektingSuite.log.txt](https://github.com/KONNEKTING/KonnektingSuite/files/160045/KonnektingSuite.log.txt)

**Comment by tuxedo0801** [comment]
Instead of host-only, try to use "bridged", which should be the recommended default (not only by Suite, but also by VBox)

The Suite depends on whatever the OS provides. There's no way to work around those problems. I'm quite sure that not only the Suite had problems in this scenario. 

Although this issue is labeled as "wontfix", it's more a "cantfix".
